# See https://www.liip.ch/en/blog/setup-drupal-and-lando-with-wsl2-on-windows
name: PROJECTNAME
recipe: drupal10
config:
  webroot: web
  php: '8.1'
  xdebug: 'develop,debug'
  composer_version: "2.5.8"
  config:
    php: lando/php.ini
#    vhosts: config/custom_vhosts.conf
proxy:
  pma:
    - pma.PROJECTNAME.lndo.site
  mailhog:
    - mailhog.PROJECTNAME.lndo.site

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://PROJECTNAME.lndo.site"
        DRUSH_OPTIONS_ROOT: '/app/web'
        XDEBUG_CONFIG: "discover_client_host=0 client_host=host.docker.internal"
  database:
    # Default to 5.7
    type: mysql
    #type: mysql:8.0
    # You can connect externally via "external_connection" info from `lando info`.
    portforward: true
    creds:
      # These credentials are used only for this specific instance.
      # You can use the same credentials for each Lando site.
      user: drupal
      password: drupal
      database: drupal

  pma:
    type: phpmyadmin
    hosts:
      - database

  mailhog:
    # Default port is 1025
    type: mailhog
    hogfrom:
      - appserver
